<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <title>Home</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid w-75">
        <label class="navbar-brand">EFCO | Цифровые решения</label>
        <ul class="navbar-nav mb-2 mb-lg-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Аккаунт
                </a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><h6 class="dropdown-header"><?=$role?></h6></li>
                    <li><a class="dropdown-item" href="<?=$router->pathFor('settings.page')?>">Настройки</a></li>

                    <?php if ($role == 'admin'): ?>
                        <li><a class="dropdown-item" href="<?=$router->pathFor('adminpanel.page')?>">Админка</a></li>
                    <?php endif; ?>

                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="<?=$router->pathFor('logout.action')?>">Выйти</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

    <div class="mt-5 justify-content-center">
        <div class="container-fluid w-75">
            <div>
                Тут должны быть фильтры
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="col">#</th>
                        <th scope="col" class="col-5">Проблема</th>
                        <th scope="col" class="col-5">Решение</th>
                        <th scope="col" style="width: 120px!important;">Оценка</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($rows as $row): ?>
                    <tr class="<?=($row['mark'] == 0 ? 'table-active' : '')?>">
                        <th scope="row"><?=$row['id']?></th>
                        <td><?=$row['problem']?></td>
                        <td><?=$row['solution']?></td>
                        <td>
                            <?php for($i = 0; $i < $row['mark']; $i++): ?>
                            <i class="bi bi-star-fill"></i>
                            <?php endfor; ?>

                            <?php for($i = $row['mark']; $i < 5; $i++): ?>
                                <i class="bi bi-star"></i>
                            <?php endfor; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>