<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>Document</title>
</head>
<body>
    <div>Поздравляю, гений, теперь ты можешь посмотреть на жидкое золото</div><br>
    <?=$role?><br>
    <?=$router->pathFor('logout.action')?>
    <a href="<?=$router->pathFor('logout.action')?>">Выйти</a>
    <img width="100%" src="/assets/liquid_gold.jpg">
</body>
</html>